baseURL = 'https://daxiong886.github.io/xiong-blog/'
title = 'Linz's Blog'
theme = 'PaperMod'
defaultContentLanguage = 'zh-cn'
enableRobotsTXT = true

[params]
    env = 'production'
    description = '记录学习、经历与思考。'
    author = 'Linz'
    mainSections = ["post"]

    defaultTheme = 'auto'
    ShowReadingTime = true
    ShowPostTags = true
    ShowBreadCrumbs = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    ShowShareButtons = true

    [params.homeInfoParams]
        Title = '你好，我是 Linz'
        Content = '在这里，记录一路走来的见闻、学习，以及那些未曾消失的念头。'

    [params.assets]
        favicon = 'favicon.svg'
        favicon16x16 = 'favicon.svg'
        favicon32x32 = 'favicon.svg'
        apple_touch_icon = 'favicon.svg'
        safari_pinned_tab = 'favicon.svg'

[[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/daxiong886'

[outputs]
    home = ['HTML', 'RSS', 'JSON']

[page]
    sortBy = "weight"


[[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 40
