baseURL = 'https://daxiong886.github.io/xiong-blog/'
title = 'Lingzhi的博客'
theme = 'PaperMod'

[params]
    mainSections = ["post"]

    ShowReadingTime = true
    ShowPostTags = true
    ShowBreadCrumbs = true

[page]
    sortBy = "weight"


[[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30